# Reference: https://cert-manager.io/docs/usage/certificate/
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: my-tls-certificate
  namespace: default
spec:
  secretName: kubemaster-me-app-tls-secret
  dnsNames:
    - "kubemaster.me"
    - "green.kubemaster.me"
    - "auth.kubemaster.me"
    - "dark.kubemaster.me"
    - "darker.kubemaster.me"
    - "oidc.kubemaster.me"
    # - "*.kubermaster.me" # <-- simpler to use this one instead of the above subdomains
  issuerRef:
    name: tls-ca-issuer
    kind: ClusterIssuer
