---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: green
  labels:
    app: cats
    type: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cats
      type: green
  template:
    metadata:
      labels:
        app: cats
        type: green
        version: v0.0.1
    spec:
      containers:
        - name: cats
          image: unfor19/docker-cats:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 50m
              memory: 128Mi
          env:
            - name: APP_NAME
              value: green
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: green
spec:
  # type: LoadBalancer
  ports:
    - name: http
      targetPort: 8080
      port: 80
  selector:
    app: cats
    type: green
---
# Hostbased - nginx, Traefik 1.7 and Traefik 2.0+
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cat
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: "http://app.kubemaster.me/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "http://app.kubemaster.me/oauth2/start?rd=$escaped_request_uri"
spec:
  rules:
    - host: app.kubemaster.me
      http:
        paths:
          - path: /
            backend:
              serviceName: green
              servicePort: http
